# POST http://localhost:3000/api/v1/user/register
# Content-Type: application/json

# {
#     "name": "superTwo",
#     "email": "sfasf@sfdsaf.com",
#     "password":"A@12345678"
# }

# {
#     "name": "admin",
#     "email": "admin@admin.ash",
#     "password":"A@12345678",
#     "role": "ADMIN"
# }

# {
#     "name": "super",
#     "email": "super@admin.ash",
#     "password":"A@12345678",
#     "role": "super_admin"
# }

# GET http://localhost:3000/api/v1/user/getAll
# Content-Type: application/json


# POST http://localhost:3000/api/v1/auth/login
# Content-Type: application/json

# {
#     "email": "super@admin.ash",
#     "password":"34534534@54A3"
# }


# PATCH http://localhost:3000/api/v1/user/update/68762b787fbd7c35cb3cba42
# Content-Type: application/json

# {
#     "name": "super admin ashraful"
# }

# POST http://localhost:3000/api/v1/auth/refresh-token
# Content-Type: application/json


# POST http://localhost:3000/api/v1/auth/logout
# Content-Type: application/json

# POST http://localhost:3000/api/v1/auth/reset-password
# Content-Type: application/json

# {
#     "oldPassword":"A@12345678",
#     "newPassword": "34534534@54A3"
# }

# POST  http://localhost:3000/api/v1/tour/create-tour-type
# Content-Type: application/json

# {
#     "name": "sfsafsaf"
# }

# GET http://localhost:3000/api/v1/tour/tour-types
# Content-Type: application/json

# PATCH  http://localhost:3000/api/v1/tour/tour-types/687bf966c671a2fb861dbb8b
# Content-Type: application/json

# {
#     "name": "edited"
# }

# GET http://localhost:3000/api/v1/tour/tour-types/687bf966c671a2fb861dbb8b
# Content-Type: application/json

# DELETE http://localhost:3000/api/v1/tour/tour-types/687c0051307c6b6b7104f051
# Content-Type: application/json

# POST http://localhost:3000/api/v1/division/create
# Content-Type: application/json

# {
#     "name": "bosila",
#     "slug": "dhaka-b",
#     "description": "Capital city of Bangladesh",
#     "thumbnail": "https://example.com/dhaka-thumbnail.jpg"
# }


# GET  http://localhost:3000/api/v1/division/687c0797321a92e6b72dc51f
# Content-Type: application/json

# {
#     "name": "Sylhet",
#     "slug": "dhaka-b",
#     "description": "Capital city of Bangladesh",
#     "thumbnail": "https://example.com/dhaka-thumbnail.jpg"
# }


# POST http://localhost:3000/api/v1/tour/create-tour
# Content-Type: application/json

# {
#   "title": "asdas sdssaTousdassr",
#   "description": "Enjoy.",
#   "images": ["https://example.com/beach.jpg"],
#   "location": "Cox's dazar",
#   "costFrom": 6500,
#   "startDate": "2025-08-01",
#   "endDate": "2025-08-05",
#   "included": ["Transport", "Meals"],
#   "excluded": ["Personal expenses"],
#   "amenities": ["Hotel", "Tour Guide"],
#   "tourPlan": ["Day 1: Arrival", "Day 2: Beach", "Day 3: Departure"],
#   "maxGuest": 20,
#   "minAge": 12,
#   "tourType": "687bfdbd885dff4318fad225",
#   "division": "687c0797321a92e6b72dc51f"
# }

# GET http://localhost:3000/api/v1/tour/687d2ce78dc01eb4c8a4baa5
# Content-Type: application/json

# GET http://localhost:3000/api/v1/tour/687d14267f8c5d7ee9e4b87e
# Content-Type: application/json

# DELETE http://localhost:3000/api/v1/tour/687d2cf88dc01eb4c8a4baaa
# Content-Type: application/json

PATCH http://localhost:3000/api/v1/tour/687d2ce78dc01eb4c8a4baa5
Content-Type: application/json

{
    "title": "updated",
    "division": "687c0797321a92e6b72dc51f"
}