# POST http://localhost:3000/api/v1/user/register
# Content-Type: application/json

# {
#     "name": "superTwo",
#     "email": "suxpssTwsdo@admin.ashs",
#     "password":"A@12345678"
# }

# {
#     "name": "admin",
#     "email": "admin@admin.ash",
#     "password":"A@12345678",
#     "role": "ADMIN"
# }

# {
#     "name": "super",
#     "email": "super@admin.ash",
#     "password":"A@12345678",
#     "role": "super_admin"
# }

# GET http://localhost:3000/api/v1/user/getAll
# Content-Type: application/json


# POST http://localhost:3000/api/v1/auth/login
# Content-Type: application/json

# {
#     "email": "super@admin.ash",
#     "password":"34534534@54A3"
# }


PATCH http://localhost:3000/api/v1/user/update/68796af945ae7269221a35b3
Content-Type: application/json

{
    "name": "Ashraful",
    "role": "admin"
}

# POST http://localhost:3000/api/v1/auth/refresh-token
# Content-Type: application/json


# POST http://localhost:3000/api/v1/auth/logout
# Content-Type: application/json

# POST http://localhost:3000/api/v1/auth/reset-password
# Content-Type: application/json

# {
#     "oldPassword":"A@12345678",
#     "newPassword": "34534534@54A3"
# }