# POST http://localhost:3000/api/v1/user/register
# Content-Type: application/json

# {
#     "name": "user",
#     "email": "user@admin.ash",
#     "password":"A@12345678"
# }

# {
#     "name": "admin",
#     "email": "admin@admin.ash",
#     "password":"A@12345678",
#     "role": "ADMIN"
# }

# {
#     "name": "super",
#     "email": "super@admin.ash",
#     "password":"A@12345678",
#     "role": "super_admin"
# }

# GET http://localhost:3000/api/v1/user/getAll
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc2MmJiNDdmYmQ3YzM1Y2IzY2JhNDYiLCJlbWFpbCI6InVzZXJAYWRtaW4uYXNoIiwicGFzc3dvcmQiOiIkMmIkMTAkcXRNNERTemRqQXZlMWY1Ulp5YWFULko2QUZkYVFuY2dCTlp1UVFNTDdpNnJweWJsOU1GUUsiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MjU3NDk3MSwiZXhwIjoxNzUyNTc1MjcxfQ.SWwWPAB4qDiPTdeBa4Cm0YVyfdSyOnJK-hJpyqYR8Iw

# POST http://localhost:3000/api/v1/auth/login
# Content-Type: application/json

# {
#     "email": "admin@admin.ash",
#     "password":"A@12345678"
# }


PATCH http://localhost:3000/api/v1/user/update/68762bb47fbd7c35cb3cba46
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc2MmI5ZjdmYmQ3YzM1Y2IzY2JhNDQiLCJlbWFpbCI6ImFkbWluQGFkbWluLmFzaCIsInBhc3N3b3JkIjoiJDJiJDEwJHQwVWxYUFhoNXVKd0xITVFHLlN2VU9hQldRZS81bVlLN0tmWkVEUVI1aU5ieGVZLkZNdzkuIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUyNjczMTEwLCJleHAiOjE3NTI5NzMxMTB9.Uz-4qfpNT2FHglJntSsfwimWrT3LCgxVvzE9ws98dN0

{
    "name": "admin cann update only its info"
}